# Generated by Django 5.1.6 on 2025-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='forward_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
