# Generated by Django 5.1.6 on 2025-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_galleryimage_forward_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='forward_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
