# Generated by Django 5.1.6 on 2025-05-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_galleryimage_forward_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='forward_link',
        ),
        migrations.AddField(
            model_name='course',
            name='forward_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
